### PR TITLE
Add missing versions

### PR DESCRIPTION
**Pull request by lubosmj**
[noissue]

### CODE REVIEW

**Comment by lubosmj** [comment]
@mdellweg, have you got any idea why the changelog builder was not able to include the versions?

**Comment by mdellweg** [comment]
It should be rendered from here: https://github.com/pulp/pulp-cli-ostree/blob/main/pyproject.toml#L5
Maybe towncrier changed something?

**Comment by lubosmj** [comment]
Yes. It seems like there is an issue with towncrier v21.9.0 (which is the version I am currently running): https://github.com/twisted/towncrier/issues/386.

**Comment by lubosmj** [comment]
Having towncrier v19.9.0 installed, all issues are gone.

**Comment by lubosmj** [comment]
@mdellweg, I am merging it without any resolution. In plugin_template, we pin towncrier to v19.9.0, presumably, to prevent such issues. There might be a similar issue when releasing a new version of pulp-cli.

**Pull request merged**
